import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt, numpy as np
accel=np.array([1.0,2.0,2.9,4.0,6.0,8.0])
mean=np.array([112.2,93.5,70.7,55.6,34.0,23.3])
std =np.array([14.1,11.7,6.5,4.3,2.8,2.2])
fig,ax=plt.subplots(figsize=(7,4.5))
ax.fill_between(accel,mean-std,mean+std,color="#c0392b",alpha=0.18,label="±1 std (6 brains)")
ax.plot(accel,mean,"o-",color="#c0392b",lw=2.2,ms=8,label="Betti-1 mean")
for x,y in zip(accel,mean): ax.annotate(f"{y:.0f}",(x,y),textcoords="offset points",xytext=(6,7),fontsize=9)
ax.set_xlabel("Acceleration factor (k-space undersampling)")
ax.set_ylabel("Betti-1 loop count (topological complexity)")
ax.set_title("Training-free, reference-free MRI quality index\nMonotonic Betti-1 degradation replicated across 6 brains (ds000102)")
ax.grid(alpha=0.3); ax.legend()
fig.tight_layout(); fig.savefig("/home/Voodooaoi/flagship_demo/mri_hero_6brain.png",dpi=140)
print("saved mri_hero_6brain.png")
